version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: infracidadao_mysql_db
    command: --lower_case_table_names=1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=infracidadao
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3001:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h127.0.0.1", "-P3306"]
      interval: 5s
      timeout: 2s
      retries: 20
